backport: Fix RHEL8.2 backport issue at and above 4.18.0-193.28.1.el8_2
Attempting to build an IFS release on the indicated zstream kernel gets
the following syntax error:

...compat_common.h:539:19: error: redefinition of 'atomic_fetch_add_unless'

Red Hat changed the API in this zstream kernel to add
atomic_fetch_add_unless() to atomic.h.  Unfortunately the base kernel for
RHEL8.2 doesn't have the API and adding the backport define
HAVE_ATOMIC_FETCH_ADD_UNLESS breaks the build on kernels prior to
4.18.0-193.28.1.el8_2.

Fix by adding a commented out $(shell...) kbuild invokation to detect the
new routine.   The packaging script edits the top level Makefile(s)
for RHEL8.2 to keep the change focused on that distro.

Signed-off-by: Mike Marciniszyn <mike.marciniszyn@cornelisnetworks.com>